spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/pcsin
    username: sa
    password: test
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100
      # show_sql: true
      format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: test

server:
  port: 8080

jwt:
  accessSecret: 'asoiwaojiw'
  refreshSecret: 'aosijdwaoij'